# Generated by Django 6.0.3 on 2026-03-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloFormativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Ciclo')),
                ('familia_profesional', models.CharField(max_length=150, verbose_name='Familia Profesional')),
                ('grado', models.CharField(max_length=100, verbose_name='Grado (Medio/Superior)')),
            ],
            options={
                'verbose_name': 'Ciclo Formativo',
                'verbose_name_plural': 'Ciclos Formativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de Centro')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(help_text='Ej: IES, CPR FPE', max_length=50)),
                ('titularidad', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=300)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web', models.URLField(blank=True, max_length=500, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('situacion', models.CharField(default='ALTA', max_length=50)),
                ('ciclos', models.ManyToManyField(blank=True, related_name='institutos', to='api.cicloformativo', verbose_name='Ciclos que imparte')),
            ],
            options={
                'verbose_name': 'Instituto',
                'verbose_name_plural': 'Institutos',
                'ordering': ['nombre'],
            },
        ),
    ]
